/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.prsolucoes.nativekit;

public class HttpClient {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HttpClient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HttpClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeKitJNI.delete_HttpClient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HttpClient() {
    this(NativeKitJNI.new_HttpClient(), true);
  }

  public String get(String url) {
    return NativeKitJNI.HttpClient_get(swigCPtr, this, url);
  }

}
